"use strict";

export const COPERNICUS_API_URL =
  "https://rapidmapping.emergency.copernicus.eu/backend/dashboard-api/public-activations/?code=EMSR884";

export const COPERNICUS_CACHE_TTL_MS = 30 * 60 * 1000;
export const COPERNICUS_MANIFEST_CACHE_KEY = "emsr884-manifest-cache-v4-inline-products";

export const DEFAULT_AOI_NUMBER = 12;

export const CARACAS = {
  id: "AOI02",
  name: "Caracas",
  center: [-66.9036, 10.4806],
  zoom: 11.2,
  pitch: 0,
  bearing: 0,
};

export const PRODUCT_ALL_KEY = "__all__";

export const COPERNICUS_URL_OVERRIDES = {
  builtUpA: "",
  builtUpP: "",
  transportationL: "",
  transportationA: "",
  facilitiesA: "",
  ancillaryCrisisInfoP: "",
  notAnalysedA: "",
  groundMovementA: "",
};

export const SOURCE_IDS = {
  builtUpA: "copernicus-built-up-a",
  builtUpP: "copernicus-built-up-p",
  transportationL: "copernicus-transportation-l",
  transportationA: "copernicus-transportation-a",
  facilitiesA: "copernicus-facilities-a",
  ancillaryCrisisInfoP: "copernicus-ancillary-crisis-info-p",
  notAnalysedA: "copernicus-not-analysed-a",
  groundMovementA: "copernicus-ground-movement-a",
  aoi: "selected-aoi-extent",
};

export const BASE_LAYER_IDS = {
  satellite: "basemap-satellite",
  street: "basemap-street",
  labels: "basemap-labels",
};

export const TRANSPORTATION_LAYER_IDS = [
  "transportation-local-road-line",
  "transportation-track-line",
  "transportation-main-road-line",
  "transportation-highway-line",
  "transportation-airfield-runway-line",
  "transportation-railway-line",
  "transportation-railway-ticks",
];

export const AOI_LAYER_IDS = [
  "aoi-fill",
  "aoi-outline",
];

export const GROUND_MOVEMENT_CLASSES = [
  { key: "groundNegHigh", id: "neg-high", value: "-0.5 to -0.2", color: "#4965ad" },
  { key: "groundNegMedium", id: "neg-medium", value: "-0.2 to -0.1", color: "#76a3c7" },
  { key: "groundNegLow", id: "neg-low", value: "-0.1 to -0.05", color: "#b4d8e7" },
  { key: "groundNearZeroNeg", id: "near-zero-neg", value: "-0.05 to 0", color: "#e4f3f8" },
  { key: "groundNearZeroPos", id: "near-zero-pos", value: "0 to 0.05", color: "#fee6a6" },
  { key: "groundPosLow", id: "pos-low", value: "0.05 to 0.1", color: "#f6ad68" },
  { key: "groundPosMedium", id: "pos-medium", value: "0.1 to 0.2", color: "#e56845" },
  { key: "groundPosHigh", id: "pos-high", value: "0.2 to 0.5", color: "#be2f2f" },
  { key: "groundAboveHigh", id: "above-high", value: "Above 0.5", color: "#9e182c" },
];

export const GROUND_MOVEMENT_LAYER_IDS = GROUND_MOVEMENT_CLASSES.flatMap((item) => [
  `ground-movement-${item.id}-fill`,
  `ground-movement-${item.id}-outline`,
]);

export const DATA_LAYER_IDS = [
  "built-up-fill",
  "built-up-outline",
  "built-up-point-halo",
  "built-up-point-circle",
  "facilities-area-fill",
  "facilities-area-outline",
  "transportation-area-fill",
  "transportation-area-outline",
  "crisis-point-halo",
  "crisis-point-circle",
  "transportation-lines",
  "transportation-other-line",
  ...TRANSPORTATION_LAYER_IDS,
  ...GROUND_MOVEMENT_LAYER_IDS,
  "not-analysed-fill",
  "not-analysed-hatch-fill",
  "not-analysed-outline",
  ...AOI_LAYER_IDS,
];

export const WANTED_LAYER_ORDER = [
  "notAnalysedA",
  "groundMovementA",
  "transportationA",
  "facilitiesA",
  "builtUpA",
  "builtUpP",
  "ancillaryCrisisInfoP",
  "transportationL",
];

export const DAMAGE_PROPERTY_FIELDS = [
  "damage_gra",
  "damage_grade",
  "Damage_Grade",
  "DAMAGE_GRA",
  "damage",
  "Damage",
];

export const COG_RENDERER_SCRIPT_URLS = {
  geotiff: "https://cdn.jsdelivr.net/npm/geotiff@2/dist-browser/geotiff.js",
  proj4: "https://cdn.jsdelivr.net/npm/proj4@2/dist/proj4.js",
};

export const translations = {
  es: {
    eyebrow: "Panel satelital público",
    title: "Terremoto de Venezuela 2026: panel geoespacial de impacto (EMSR884)",
    subtitle: "Interfaz no oficial para evaluaciones satelitales de Copernicus (gradación y movimiento del terreno).",
    mobileTitle: "Terremoto de Venezuela 2026: panel geoespacial de impacto (EMSR884)",
    safetyTitle: "Aviso de seguridad pública",
    safetyText: "Este panel es solo para información pública. No es una herramienta oficial de rescate, evacuación o respuesta de emergencia. Siga siempre a las autoridades locales.",
    areasTitle: "Áreas de interés",
    caracasStatus: "Activo — datos satelitales disponibles",
    processing: "Procesando datos satelitales",
    otherCities: "Otras AOI",
    basemapTitle: "Mapa base",
    satelliteBasemap: "Satélite + calles",
    streetBasemap: "Calles OSM suaves",
    satelliteLabels: "Mostrar nombres de calles sobre satélite",
    basemapNote: "Prototipo: satélite por Esri; calles claras por CARTO/OpenStreetMap. Para tráfico masivo, cambiar a un proveedor de teselas de producción.",
    dataStatusTitle: "Estado de los datos",
    officialSource: "Fuente oficial Copernicus EMSR884",
    activationCode: "Activación",
    aoiProduct: "Área / producto",
    copernicusDelivery: "Entrega de Copernicus",
    satelliteAcquisition: "Imagen satelital",
    lastChecked: "Última comprobación",
    lastSuccessfulLoad: "Carga correcta del visor",
    cacheStatus: "Cache",
    refreshData: "Actualizar datos",
    dataFreshnessNote: "Este visor comprueba el manifiesto oficial de Copernicus como máximo cada 30 minutos por navegador. La entrega de Copernicus indica cuándo Copernicus publicó el producto; la última comprobación indica cuándo este visor revisó la fuente oficial.",
    cacheLive: "Directo",
    cacheFresh: "Cache reciente",
    cacheStale: "Cache antiguo",
    newData: "Nuevo",
    recentData: "Reciente",
    olderData: "Revisar fecha",
    notAvailable: "No disponible",
    legendTitle: "Leyenda",
    possiblyDamaged: "Posible daño",
    confirmedDamaged: "Daño / daño confirmado",
    destroyed: "Destruido",
    roads: "Carreteras / transporte",
    notAnalysed: "No analizado / nubes",
    dataTitle: "Aclaración de datos",
    dataText: "Las clases de daño son evaluaciones remotas por satélite y pueden requerir verificación en campo. Amarillo significa posible daño, no destrucción confirmada. El tramado gris significa que el área no fue analizada porque la vista satelital estaba obstruida o no disponible.",
    source: "Fuente",
    unofficial: "Interfaz no oficial de interés público. No se recopilan datos de rescate ni de víctimas.",
    builtBy: "Construido por YIN Renlong · Interfaz no oficial de interés público usando datos públicos de Copernicus EMSR884.",
    issueText: "Si encuentra un problema, visite el proyecto en GitHub.",
    footerCredit: "Interfaz pública no oficial. No recopila datos de rescate, víctimas ni personas desaparecidas. Si encuentra un problema,",
    footerGithubLink: "visite el proyecto en GitHub",
    footerAuthorPrefix: "Construido por",
    footerPeriod: ".",
    loadingTitle: "Cargando datos satelitales",
    loadingText: "Obteniendo capas públicas de Copernicus EMSR884.",
    largeLayerLoadingTitle: "Cargando una capa geoespacial grande",
    largeLayerLoadingText: "Se está descargando una capa grande de Copernicus. La primera carga puede tardar en conexiones lentas; al volver a esta AOI en la misma sesión del navegador se reutilizarán los datos en caché cuando sea posible.",
    loadedTitle: "Datos satelitales cargados",
    loadedText: "Capas públicas cargadas correctamente.",
    unavailableTitle: "Datos satelitales temporalmente no disponibles",
    unavailableText: "No se pudieron cargar las capas públicas de Copernicus. Puede ser un problema temporal, CORS o un cambio en el manifiesto de datos.",
    retry: "Reintentar",
  },

  en: {
    eyebrow: "Public satellite dashboard",
    title: "Venezuela 2026 Earthquake: Geospatial Impact Dashboard (EMSR884)",
    subtitle: "Unofficial interface for Copernicus satellite assessments (grading and ground movement).",
    mobileTitle: "Venezuela 2026 Earthquake: Geospatial Impact Dashboard (EMSR884)",
    safetyTitle: "Public safety notice",
    safetyText: "This dashboard is for public information only. It is not an official rescue, evacuation, or emergency response tool. Always follow local authorities.",
    areasTitle: "Areas of interest",
    caracasStatus: "Active — satellite data available",
    processing: "Processing satellite data",
    otherCities: "Other AOIs",
    basemapTitle: "Basemap",
    satelliteBasemap: "Satellite + streets",
    streetBasemap: "Muted OSM",
    satelliteLabels: "Show street names over satellite",
    basemapNote: "Prototype: satellite imagery by Esri; clean street map by CARTO/OpenStreetMap. For massive traffic, replace with a production tile provider.",
    dataStatusTitle: "Data status",
    officialSource: "Official Copernicus EMSR884 source",
    activationCode: "Activation",
    aoiProduct: "Area / product",
    copernicusDelivery: "Copernicus delivery",
    satelliteAcquisition: "Satellite image",
    lastChecked: "Last checked",
    lastSuccessfulLoad: "Last successful dashboard load",
    cacheStatus: "Cache",
    refreshData: "Refresh data",
    dataFreshnessNote: "This dashboard checks the official Copernicus manifest at most every 30 minutes per browser. Copernicus delivery means when Copernicus published the product; last checked means when this dashboard checked the official source.",
    cacheLive: "Live",
    cacheFresh: "Fresh cache",
    cacheStale: "Old cache",
    newData: "New",
    recentData: "Recent",
    olderData: "Check date",
    notAvailable: "Not available",
    legendTitle: "Legend",
    possiblyDamaged: "Possibly damaged",
    confirmedDamaged: "Damaged / confirmed damage",
    destroyed: "Destroyed",
    roads: "Roads / transport lines",
    notAnalysed: "Not analysed / clouds",
    dataTitle: "Data clarification",
    dataText: "Damage classes are remote satellite assessments and may require field verification. Yellow means possibly damaged, not confirmed destruction. Gray hatching means the area was not analysed because the satellite view was obstructed or unavailable.",
    source: "Source",
    unofficial: "Unofficial public-interest interface. No rescue or casualty data is collected.",
    builtBy: "Built by YIN Renlong · Unofficial public-interest interface using public Copernicus EMSR884 data.",
    issueText: "If you find an issue, please visit the GitHub project.",
    footerCredit: "Unofficial public interface. No rescue, casualty, or missing-person data is collected. If you find an issue,",
    footerGithubLink: "visit the GitHub project",
    footerAuthorPrefix: "Built by",
    footerPeriod: ".",
    loadingTitle: "Loading satellite data",
    loadingText: "Fetching Copernicus EMSR884 public layers.",
    largeLayerLoadingTitle: "Loading large geospatial layer",
    largeLayerLoadingText: "Downloading a large Copernicus layer. The first load may take some time on slower connections; revisiting this AOI in the same browser session will reuse cached data when possible.",
    loadedTitle: "Satellite data loaded",
    loadedText: "Public layers loaded successfully.",
    unavailableTitle: "Satellite data temporarily unavailable",
    unavailableText: "The public Copernicus layers could not be loaded. This may be temporary, caused by CORS, or caused by a change in the data manifest.",
    retry: "Retry",
  },

  it: {
    eyebrow: "Dashboard satellitare pubblico",
    title: "Terremoto in Venezuela 2026: dashboard geospaziale dell’impatto (EMSR884)",
    subtitle: "Interfaccia non ufficiale per le valutazioni satellitari Copernicus (classificazione e movimento del suolo).",
    mobileTitle: "Terremoto in Venezuela 2026: dashboard geospaziale dell’impatto (EMSR884)",
    safetyTitle: "Avviso di sicurezza pubblica",
    safetyText: "Questa dashboard è solo a scopo informativo. Non è uno strumento ufficiale di soccorso, evacuazione o risposta alle emergenze. Seguire sempre le autorità locali.",
    areasTitle: "Aree di interesse",
    caracasStatus: "Attivo — dati satellitari disponibili",
    processing: "Elaborazione dati satellitari",
    otherCities: "Altre AOI",
    basemapTitle: "Mappa base",
    satelliteBasemap: "Satellite + strade",
    streetBasemap: "OSM morbida",
    satelliteLabels: "Mostra i nomi delle strade sul satellite",
    basemapNote: "Prototipo: immagini satellitari di Esri; strade chiare di CARTO/OpenStreetMap. Per traffico massivo, usare un provider di tile di produzione.",
    dataStatusTitle: "Stato dei dati",
    officialSource: "Fonte ufficiale Copernicus EMSR884",
    activationCode: "Attivazione",
    aoiProduct: "Area / prodotto",
    copernicusDelivery: "Consegna Copernicus",
    satelliteAcquisition: "Immagine satellitare",
    lastChecked: "Ultimo controllo",
    lastSuccessfulLoad: "Ultimo caricamento riuscito",
    cacheStatus: "Cache",
    refreshData: "Aggiorna dati",
    dataFreshnessNote: "Questa dashboard controlla il manifesto ufficiale Copernicus al massimo ogni 30 minuti per browser. La consegna Copernicus indica quando Copernicus ha pubblicato il prodotto; l’ultimo controllo indica quando questa dashboard ha verificato la fonte ufficiale.",
    cacheLive: "Diretto",
    cacheFresh: "Cache recente",
    cacheStale: "Cache vecchia",
    newData: "Nuovo",
    recentData: "Recente",
    olderData: "Controllare data",
    notAvailable: "Non disponibile",
    legendTitle: "Legenda",
    possiblyDamaged: "Possibile danno",
    confirmedDamaged: "Danno / danno confermato",
    destroyed: "Distrutto",
    roads: "Strade / trasporti",
    notAnalysed: "Non analizzato / nuvole",
    dataTitle: "Chiarimento sui dati",
    dataText: "Le classi di danno sono valutazioni satellitari remote e possono richiedere verifica sul campo. Il giallo indica possibile danno, non distruzione confermata. Il tratteggio grigio indica un'area non analizzata perché la vista satellitare era ostruita o non disponibile.",
    source: "Fonte",
    unofficial: "Interfaccia non ufficiale di interesse pubblico. Non vengono raccolti dati su soccorsi o vittime.",
    builtBy: "Realizzato da YIN Renlong · Interfaccia non ufficiale di interesse pubblico basata su dati pubblici Copernicus EMSR884.",
    issueText: "Se trovi un problema, visita il progetto su GitHub.",
    footerCredit: "Interfaccia pubblica non ufficiale. Non vengono raccolti dati su soccorsi, vittime o persone scomparse. Se trovi un problema,",
    footerGithubLink: "visita il progetto su GitHub",
    footerAuthorPrefix: "Realizzato da",
    footerPeriod: ".",
    loadingTitle: "Caricamento dati satellitari",
    loadingText: "Recupero dei layer pubblici Copernicus EMSR884.",
    largeLayerLoadingTitle: "Caricamento di un layer geospaziale grande",
    largeLayerLoadingText: "Download di un layer Copernicus di grandi dimensioni. Il primo caricamento può richiedere tempo su connessioni lente; tornando a questa AOI nella stessa sessione del browser, i dati in cache verranno riutilizzati quando possibile.",
    loadedTitle: "Dati satellitari caricati",
    loadedText: "Layer pubblici caricati correttamente.",
    unavailableTitle: "Dati satellitari temporaneamente non disponibili",
    unavailableText: "Non è stato possibile caricare i layer pubblici Copernicus. Potrebbe essere un problema temporaneo, CORS o una modifica del manifesto dati.",
    retry: "Riprova",
  },

  zh: {
    eyebrow: "公共卫星仪表板",
    title: "2026 年委内瑞拉地震：地理空间影响仪表板（EMSR884）",
    subtitle: "Copernicus 卫星评估（分级评估与地表位移）的非官方界面。",
    mobileTitle: "2026 年委内瑞拉地震：地理空间影响仪表板（EMSR884）",
    safetyTitle: "公共安全提示",
    safetyText: "本仪表板仅供公众参考，不是官方救援、疏散或应急响应工具。请始终遵循当地主管部门的指示。",
    areasTitle: "关注区域",
    caracasStatus: "可用 — 卫星数据已开放",
    processing: "卫星数据处理中",
    otherCities: "其他 AOI",
    basemapTitle: "底图",
    satelliteBasemap: "卫星 + 街道",
    streetBasemap: "柔和 OSM",
    satelliteLabels: "在卫星图上显示街道名称",
    basemapNote: "原型：卫星影像来自 Esri；清晰街道地图来自 CARTO/OpenStreetMap。若访问量很大，应更换为生产级瓦片服务。",
    dataStatusTitle: "数据状态",
    officialSource: "Copernicus EMSR884 官方来源",
    activationCode: "激活编号",
    aoiProduct: "区域 / 产品",
    copernicusDelivery: "Copernicus 发布时间",
    satelliteAcquisition: "卫星影像时间",
    lastChecked: "上次检查",
    lastSuccessfulLoad: "仪表板成功加载时间",
    cacheStatus: "缓存",
    refreshData: "刷新数据",
    dataFreshnessNote: "本仪表板每个浏览器最多每 30 分钟检查一次 Copernicus 官方清单。Copernicus 发布时间表示官方发布产品的时间；上次检查表示本仪表板检查官方来源的时间。",
    cacheLive: "实时",
    cacheFresh: "新缓存",
    cacheStale: "旧缓存",
    newData: "新数据",
    recentData: "较新",
    olderData: "请检查日期",
    notAvailable: "不可用",
    legendTitle: "图例",
    possiblyDamaged: "可能受损",
    confirmedDamaged: "受损 / 已确认受损",
    destroyed: "已毁",
    roads: "道路 / 交通线",
    notAnalysed: "未分析 / 云层遮挡",
    dataTitle: "数据说明",
    dataText: "损毁等级来自卫星遥感评估，可能需要现场核实。黄色表示可能受损，不代表已确认毁坏。灰色斜线表示该区域因卫星视野受阻或数据不可用而未被分析。",
    source: "来源",
    unofficial: "非官方公益界面。不收集救援或伤亡数据。",
    builtBy: "由 YIN Renlong 构建 · 使用 Copernicus EMSR884 公共数据的非官方公益界面。",
    issueText: "如果发现问题，请访问 GitHub 项目。",
    footerCredit: "非官方公益界面。不收集救援、伤亡或失踪人员数据。如发现问题，请",
    footerGithubLink: "访问 GitHub 项目",
    footerAuthorPrefix: "构建者",
    footerPeriod: "。",
    loadingTitle: "正在加载卫星数据",
    loadingText: "正在获取 Copernicus EMSR884 公共图层。",
    largeLayerLoadingTitle: "正在加载大型地理空间图层",
    largeLayerLoadingText: "正在下载较大的 Copernicus 图层。首次加载在较慢网络下可能需要一些时间；在同一浏览器会话中再次打开该 AOI 时，将尽可能复用缓存数据。",
    loadedTitle: "卫星数据已加载",
    loadedText: "公共图层已成功加载。",
    unavailableTitle: "卫星数据暂时不可用",
    unavailableText: "无法加载 Copernicus 公共图层。可能是临时问题、CORS 限制或数据清单结构发生变化。",
    retry: "重试",
  },
};

export const supplementalTranslations = {
  es: {
    aoiAvailable: "Disponible — capas de daño publicadas",
    aoiInProgress: "En progreso",
    aoiPlanned: "Planificado / esperando confirmación",
    aoiNotProduced: "No producido",
    aoiProcessing: "Esperando capas públicas",
    allProducts: "Todos los productos",
    aoiUnavailableTitle: "AOI aún sin capas públicas",
    aoiUnavailableText: "Copernicus ya listó esta AOI, pero las capas vectoriales públicas aún no están publicadas. El marcador se activará cuando Copernicus publique los datos.",
    builtUpGrading: "Evaluación de edificaciones",
    builtUpPoints: "Puntos de edificaciones",
    transportationGrading: "Red vial y ferroviaria",
    generalInformation: "Información general",
    basemapNoteButton: "Nota sobre el mapa base",
    productsTitle: "Productos",
    builtUpArea: "Área edificada",
    crisisPoints: "Puntos de crisis",
    blockedRoadInterruption: "Carretera bloqueada / interrupción",
    facilitiesArea: "Área de instalaciones",
    transportationArea: "Área de transporte",
    airfieldAndHeliportDamaged: "Aeródromo y helipuerto, dañado",
    sourceImagery: "Imagen fuente de Copernicus",
    sourceImageryCompareSubtitle: "Comparar adquisiciones oficiales",
    sourceImagerySingleSubtitle: "Imagen oficial disponible",
    overlayMultipleImages: "Superponer múltiples imágenes",
    earlierAcquisition: "Anterior",
    latestAcquisition: "Más reciente",
    sourceImageryAcquisition: "Adquisición",
    sourceImageryActive: "Activa",
    sourceImageryInactive: "Sin imagen activa",
    sourceImageryAvailable: "Disponible",
    sourceImageryActiveMultiple: "Imágenes activas",
    collapseImageryPanel: "Contraer panel de imágenes",
    expandImageryPanel: "Expandir panel de imágenes",
    sourceImageryLoadingTitle: "Cargando imagen fuente de Copernicus",
    sourceImageryLoadingText: "Preparando teselas de la imagen oficial. La imagen se carga bajo demanda y puede tardar en conexiones lentas.",
    sourceImageryLoadedTitle: "Imagen fuente cargada",
    sourceImageryLoadedText: "La imagen fuente de Copernicus está visible en el mapa.",
    sourceImageryErrorTitle: "No se pudo cargar la imagen fuente",
    sourceImageryErrorText: "El navegador no pudo leer esta imagen COG. Puede abrir el archivo TIFF desde el enlace de la leyenda.",
    sourceImageOnly: "Imagen fuente disponible",
    noDisplayableLayers: "No hay capas vectoriales visibles para el producto seleccionado.",
    groundMovementGrading: "Movimiento del terreno",
    groundMovementM: "Movimiento del terreno (m)",
    gmNegHigh: "-0.5 a -0.2",
    gmNegMedium: "-0.2 a -0.1",
    gmNegLow: "-0.1 a -0.05",
    gmNearZeroNeg: "-0.05 a 0",
    gmNearZeroPos: "0 a 0.05",
    gmPosLow: "0.05 a 0.1",
    gmPosMedium: "0.1 a 0.2",
    gmPosHigh: "0.2 a 0.5",
    gmAboveHigh: "Más de 0.5",
    highwayNoVisibleDamage: "Autopista, sin daño visible",
    mainRoadNoVisibleDamage: "Vía principal, sin daño visible",
    localRoadNoVisibleDamage: "Vía local, sin daño visible",
    trackNoVisibleDamage: "Camino / pista, sin daño visible",
    airfieldRunwayNoVisibleDamage: "Pista de aeródromo, sin daño visible",
    railwayNoVisibleDamage: "Ferrocarril / metro, sin daño visible",
    areaOfInterest: "Área de interés",
    collapseLegend: "Contraer leyenda",
    expandLegend: "Expandir leyenda",
  },

  en: {
    aoiAvailable: "Available — damage layers published",
    aoiInProgress: "In progress",
    aoiPlanned: "Planned / waiting confirmation",
    aoiNotProduced: "Not produced",
    aoiProcessing: "Waiting for public layers",
    allProducts: "All products",
    aoiUnavailableTitle: "AOI public layers not available yet",
    aoiUnavailableText: "Copernicus has listed this AOI, but public vector layers are not published yet. This placeholder will become active when Copernicus publishes the data.",
    builtUpGrading: "Built Up Grading",
    builtUpPoints: "Built Up Points",
    transportationGrading: "Road and rail network",
    generalInformation: "General Information",
    basemapNoteButton: "Basemap note",
    productsTitle: "Products",
    builtUpArea: "Built Up Area",
    crisisPoints: "Crisis Points",
    blockedRoadInterruption: "Blocked road / interruption",
    facilitiesArea: "Facilities Area",
    transportationArea: "Transportation Area",
    airfieldAndHeliportDamaged: "Airfield and Heliport, Damaged",
    sourceImagery: "Copernicus source imagery",
    sourceImageryCompareSubtitle: "Compare official acquisition dates",
    sourceImagerySingleSubtitle: "Official source image available",
    overlayMultipleImages: "Overlay multiple images",
    earlierAcquisition: "Earlier",
    latestAcquisition: "Latest",
    sourceImageryAcquisition: "Acquisition",
    sourceImageryActive: "Active",
    sourceImageryInactive: "No image active",
    sourceImageryAvailable: "Available",
    sourceImageryActiveMultiple: "Active images",
    collapseImageryPanel: "Collapse imagery panel",
    expandImageryPanel: "Expand imagery panel",
    sourceImageryLoadingTitle: "Loading Copernicus source image",
    sourceImageryLoadingText: "Preparing official image tiles. The image loads on demand and may take time on slower connections.",
    sourceImageryLoadedTitle: "Source image loaded",
    sourceImageryLoadedText: "The Copernicus source image is visible on the map.",
    sourceImageryErrorTitle: "Could not load source image",
    sourceImageryErrorText: "The browser could not read this COG image. You can open the TIFF file from the legend link.",
    sourceImageOnly: "Source image available",
    noDisplayableLayers: "No visible vector layers are available for the selected product.",
    groundMovementGrading: "Ground Movement",
    groundMovementM: "Ground Movement (m)",
    gmNegHigh: "-0.5 to -0.2",
    gmNegMedium: "-0.2 to -0.1",
    gmNegLow: "-0.1 to -0.05",
    gmNearZeroNeg: "-0.05 to 0",
    gmNearZeroPos: "0 to 0.05",
    gmPosLow: "0.05 to 0.1",
    gmPosMedium: "0.1 to 0.2",
    gmPosHigh: "0.2 to 0.5",
    gmAboveHigh: "Above 0.5",
    highwayNoVisibleDamage: "Highway, No visible damage",
    mainRoadNoVisibleDamage: "Main road, No visible damage",
    localRoadNoVisibleDamage: "Local road, No visible damage",
    trackNoVisibleDamage: "Track, No visible damage",
    airfieldRunwayNoVisibleDamage: "Airfield runway, No visible damage",
    railwayNoVisibleDamage: "Railway / subway, No visible damage",
    areaOfInterest: "Area of Interest",
    collapseLegend: "Collapse legend",
    expandLegend: "Expand legend",
  },

  it: {
    aoiAvailable: "Disponibile — layer di danno pubblicati",
    aoiInProgress: "In corso",
    aoiPlanned: "Pianificato / in attesa di conferma",
    aoiNotProduced: "Non prodotto",
    aoiProcessing: "In attesa dei layer pubblici",
    allProducts: "Tutti i prodotti",
    aoiUnavailableTitle: "Layer pubblici AOI non ancora disponibili",
    aoiUnavailableText: "Copernicus ha elencato questa AOI, ma i layer vettoriali pubblici non sono ancora pubblicati. Il segnaposto si attiverà quando Copernicus pubblicherà i dati.",
    builtUpGrading: "Valutazione edifici",
    builtUpPoints: "Punti edificati",
    transportationGrading: "Rete stradale e ferroviaria",
    generalInformation: "Informazioni generali",
    basemapNoteButton: "Nota sulla mappa base",
    productsTitle: "Prodotti",
    builtUpArea: "Area edificata",
    crisisPoints: "Punti di crisi",
    blockedRoadInterruption: "Strada bloccata / interruzione",
    facilitiesArea: "Area delle strutture",
    transportationArea: "Area di trasporto",
    airfieldAndHeliportDamaged: "Aeroporto ed eliporto, danneggiato",
    sourceImagery: "Immagine sorgente Copernicus",
    sourceImageryCompareSubtitle: "Confronta le acquisizioni ufficiali",
    sourceImagerySingleSubtitle: "Immagine ufficiale disponibile",
    overlayMultipleImages: "Sovrapponi più immagini",
    earlierAcquisition: "Precedente",
    latestAcquisition: "Più recente",
    sourceImageryAcquisition: "Acquisizione",
    sourceImageryActive: "Attiva",
    sourceImageryInactive: "Nessuna immagine attiva",
    sourceImageryAvailable: "Disponibile",
    sourceImageryActiveMultiple: "Immagini attive",
    collapseImageryPanel: "Comprimi pannello immagini",
    expandImageryPanel: "Espandi pannello immagini",
    sourceImageryLoadingTitle: "Caricamento immagine sorgente Copernicus",
    sourceImageryLoadingText: "Preparazione delle tile dell’immagine ufficiale. L’immagine viene caricata su richiesta e può richiedere tempo su connessioni lente.",
    sourceImageryLoadedTitle: "Immagine sorgente caricata",
    sourceImageryLoadedText: "L’immagine sorgente Copernicus è visibile sulla mappa.",
    sourceImageryErrorTitle: "Impossibile caricare l’immagine sorgente",
    sourceImageryErrorText: "Il browser non ha potuto leggere questa immagine COG. Puoi aprire il file TIFF dal link nella legenda.",
    sourceImageOnly: "Immagine sorgente disponibile",
    noDisplayableLayers: "Non sono disponibili layer vettoriali visibili per il prodotto selezionato.",
    groundMovementGrading: "Movimento del suolo",
    groundMovementM: "Movimento del suolo (m)",
    gmNegHigh: "-0.5 a -0.2",
    gmNegMedium: "-0.2 a -0.1",
    gmNegLow: "-0.1 a -0.05",
    gmNearZeroNeg: "-0.05 a 0",
    gmNearZeroPos: "0 a 0.05",
    gmPosLow: "0.05 a 0.1",
    gmPosMedium: "0.1 a 0.2",
    gmPosHigh: "0.2 a 0.5",
    gmAboveHigh: "Oltre 0.5",
    highwayNoVisibleDamage: "Autostrada, nessun danno visibile",
    mainRoadNoVisibleDamage: "Strada principale, nessun danno visibile",
    localRoadNoVisibleDamage: "Strada locale, nessun danno visibile",
    trackNoVisibleDamage: "Pista / sentiero, nessun danno visibile",
    airfieldRunwayNoVisibleDamage: "Pista aeroportuale, nessun danno visibile",
    railwayNoVisibleDamage: "Ferrovia / metro, nessun danno visibile",
    areaOfInterest: "Area di interesse",
    collapseLegend: "Comprimi legenda",
    expandLegend: "Espandi legenda",
  },

  zh: {
    aoiAvailable: "可用 — 损毁图层已发布",
    aoiInProgress: "处理中",
    aoiPlanned: "已计划 / 等待确认",
    aoiNotProduced: "未生产",
    aoiProcessing: "等待公共图层",
    allProducts: "全部产品",
    aoiUnavailableTitle: "该 AOI 公共图层尚不可用",
    aoiUnavailableText: "Copernicus 已列出该 AOI，但公共矢量图层尚未发布。Copernicus 发布数据后，此占位项会自动变为可用。",
    builtUpGrading: "建筑物评估",
    builtUpPoints: "建筑物点",
    transportationGrading: "道路与铁路网络",
    generalInformation: "一般信息",
    basemapNoteButton: "底图说明",
    productsTitle: "产品",
    builtUpArea: "建筑物面",
    crisisPoints: "危机点",
    blockedRoadInterruption: "道路阻断 / 中断",
    facilitiesArea: "设施面",
    transportationArea: "交通设施面",
    airfieldAndHeliportDamaged: "机场与直升机场，受损",
    sourceImagery: "Copernicus 源影像",
    sourceImageryCompareSubtitle: "比较官方影像获取时间",
    sourceImagerySingleSubtitle: "官方源影像可用",
    overlayMultipleImages: "叠加多幅影像",
    earlierAcquisition: "较早",
    latestAcquisition: "最新",
    sourceImageryAcquisition: "影像",
    sourceImageryActive: "已启用",
    sourceImageryInactive: "未启用影像",
    sourceImageryAvailable: "可选择",
    sourceImageryActiveMultiple: "已启用影像",
    collapseImageryPanel: "收起影像面板",
    expandImageryPanel: "展开影像面板",
    sourceImageryLoadingTitle: "正在加载 Copernicus 源影像",
    sourceImageryLoadingText: "正在准备官方影像瓦片。影像按需加载，在较慢网络下可能需要一些时间。",
    sourceImageryLoadedTitle: "源影像已加载",
    sourceImageryLoadedText: "Copernicus 源影像已显示在地图上。",
    sourceImageryErrorTitle: "无法加载源影像",
    sourceImageryErrorText: "浏览器无法读取该 COG 影像。您仍可通过图例中的链接打开 TIFF 文件。",
    sourceImageOnly: "源影像可用",
    noDisplayableLayers: "所选产品没有可显示的矢量图层。",
    groundMovementGrading: "地表位移",
    groundMovementM: "地表位移（米）",
    gmNegHigh: "-0.5 至 -0.2",
    gmNegMedium: "-0.2 至 -0.1",
    gmNegLow: "-0.1 至 -0.05",
    gmNearZeroNeg: "-0.05 至 0",
    gmNearZeroPos: "0 至 0.05",
    gmPosLow: "0.05 至 0.1",
    gmPosMedium: "0.1 至 0.2",
    gmPosHigh: "0.2 至 0.5",
    gmAboveHigh: "大于 0.5",
    highwayNoVisibleDamage: "高速路，无可见损毁",
    mainRoadNoVisibleDamage: "主干道，无可见损毁",
    localRoadNoVisibleDamage: "本地道路，无可见损毁",
    trackNoVisibleDamage: "小路 / 便道，无可见损毁",
    airfieldRunwayNoVisibleDamage: "机场跑道，无可见损毁",
    railwayNoVisibleDamage: "铁路 / 地铁，无可见损毁",
    areaOfInterest: "关注区域",
    collapseLegend: "收起图例",
    expandLegend: "展开图例",
  },
};
